# Generated by Django 2.0 on 2018-01-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=20)),
                ('localidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('tipo_paquete', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=20)),
                ('logo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tiene_ejemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.ejemplar')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=9)),
                ('edad', models.PositiveSmallIntegerField()),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('n_ruedas', models.PositiveSmallIntegerField()),
                ('potencia', models.PositiveSmallIntegerField()),
                ('n_asientos', models.PositiveSmallIntegerField()),
                ('n_puertas', models.PositiveSmallIntegerField()),
                ('anyo_salida', models.PositiveSmallIntegerField()),
                ('precio', models.FloatField(max_length=8)),
                ('foto', models.CharField(max_length=50)),
                ('id_fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.fabricante')),
            ],
        ),
        migrations.AddField(
            model_name='tiene_ejemplar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.usuario'),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.usuario'),
        ),
    ]
