# Generated by Django 2.0 on 2018-02-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_auto_20180213_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(default='img/coches/coche.png', upload_to='img/coches/'),
        ),
    ]
